### ISSUE TITLE
make !tag include similarities

### ISSUE THREAD

**Issue by robo-gowon** [gowon-bot/gowon#295]
such as kpop, k pop, k-pop

## Notes from Gowon:

[Jump to message](https://discord.com/channels/768596255697272862/791759992134303744/1035359844464603168)

**Author**: john! (johnanaphone)
**Ran at**: 1:10AM on October 28th, 2022
**Channel:** \#bots
**Guild**: Music Orbit

**Comment by jivison** [comment]
Might wanna include a flag to do only exact matching
