### ISSUE TITLE
add similar tag list to !gi

### ISSUE THREAD

**Issue by robo-gowon** [gowon-bot/gowon#300]
## Notes from Gowon:

[Jump to message](https://discord.com/channels/768596255697272862/791759992134303744/1042354155626446848)

**Author**: john! (average zillennial:)
**Ran at**: 8:23AM on November 16th, 2022
**Channel:** \#bots
**Guild**: Music Orbit

**Comment by jivison** [comment]
Maybe when you ask for a non-existent tag that has registered similar tags, it shows something like "did you mean....?"
