### ISSUE TITLE
"An unknown error occurred" when running !ai for certain artists

### ISSUE THREAD

**Issue by robo-gowon** [gowon-bot/gowon#303]
## Notes from Gowon:

[Jump to message](https://discord.com/channels/768596255697272862/791759992134303744/1043071732543655968)

**Author**: john! (average zillennial:)
**Ran at**: 7:54AM on November 18th, 2022
**Channel:** \#bots
**Guild**: Music Orbit

**Comment by jivison** [comment]
Happens with: 
- Hourmelts
