### ISSUE TITLE
use Spotify cover when lastfm one is not available

### ISSUE THREAD

**Issue by robo-gowon** [gowon-bot/gowon#318]
## Notes from Gowon:

[Jump to message](https://discord.com/channels/768596255697272862/768596255697272865/1053101441683828798)

**Author**: john! (me when I'm in a me when a)
**Ran at**: 12:09AM on December 16th, 2022
**Channel:** \#general
**Guild**: Music Orbit

**Comment by jivison** [comment]
Closed by https://github.com/gowon-bot/gowon/issues/320
