### ISSUE TITLE
black uses indexed data emoji not visible for AMOLED theme users

### ISSUE THREAD

**Issue by robo-gowon** [gowon-bot/gowon#319]
## Notes from Gowon:

[Jump to message](https://discord.com/channels/768596255697272862/768596255697272865/1055157904451313726)

**Author**: john! (me when I'm in a me when a)
**Ran at**: 4:20PM on December 21st, 2022
**Channel:** \#general
**Guild**: Music Orbit

**Comment by jivison** [comment]
Not worried about this as it's an experimental feature. Will re-open if Discord ever provides theme context for emojis
