### ISSUE TITLE
!fuck

### ISSUE THREAD

**Issue by robo-gowon** [gowon-bot/gowon#348]
## Notes from Gowon:

[Jump to message](https://discord.com/channels/260438376270921729/788757195575525407/1084982937663066273)

**Author**: john! (jogn)
**Ran at**: 11:34PM on March 13th, 2023
**Channel:** \#fmbot
**Guild**: Last.fm

**Comment by jivison** [comment]
Add `!fuck` as an alias for `!unove` and `!unfuck` as an alias for `!love`.

`"unfuck"` needs to be added to the `alias` property of the `Love` command.
`"fuck"` needs to be added to the unlove `variation` array under variations in the `Love` command
