### ISSUE TITLE
Update emoji validation to use message reacting instead of djs cache

### ISSUE THREAD

**Issue by robo-gowon** [gowon-bot/gowon#451]
## Notes from Gowon:

[Jump to message](https://discord.com/channels/768596255697272862/791759992134303744/1159974210349826060)

**Author**: mahjogn (punctuation pilled)
**Ran at**: 10:03PM on October 6th, 2023
**Channel:** \#bots
**Guild**: Music Orbit

**Comment by jivison** [comment]
Try the cache first, but if it's not there try reacting
